modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "GNU LGPLv3"

[[mods]]
modId = "miningunderworld"
version = "${version}"
displayName = "Mining Underworld"
authors = "MORIMORI0317, nin8995, Raindazo"
credits = "FelNull developers"
description = '''
The ikisugi mining dimension mod...
'''
#logoFile = ""

[[dependencies.miningunderworld]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.miningunderworld]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.miningunderworld]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.73,)"
ordering = "AFTER"
side = "BOTH"